### ISSUE TITLE
Mute doesent work Serverwide. Testing soon.

### ISSUE THREAD

**Issue by RobStyling** [L0RD-K/Suzu#13]

**Comment by L0RD-K** [comment]
Need to create the Muted role?

**Comment by RobStyling** [comment]
No thats not the Issue.
The Issue is that `message.guild.get is not a function` 
Working on a Fix in now. 🚀

**Comment by RobStyling** [comment]
fixed with Commit 3853d35dc9c30a3f52c740abb53bfca9683a35c4 . Closing Issue.
